include: package:lints/recommended.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.solana.dart"
    - "test/.generated/**"
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    always_declare_return_types: true
    avoid_annotating_with_dynamic: true
    avoid_dynamic_calls: true
    avoid_relative_lib_imports: true
    directives_ordering: true
    prefer_final_locals: true
    prefer_relative_imports: true
    public_member_api_docs: true
