builders:
  bundled:
    import: "package:solana_idl_codegen/builder.dart"
    builder_factories: ["solanaIdlBundledBuilder"]
    build_extensions:
      "lib/idl/{{}}.json":
        - "lib/generated/{{}}_solana.dart"
    auto_apply: none
    build_to: source
    defaults:
      generate_for:
        - "lib/idl/**.json"
      options:
        type_prefix: "auto"
        type_suffix: ""

  modular:
    import: "package:solana_idl_codegen/builder.dart"
    builder_factories: ["solanaIdlModularBuilder"]
    build_extensions:
      "lib/idl/{{}}.json":
        - "lib/generated/{{}}_solana.dart"
        - "lib/generated/{{}}_solana_support.dart"
        - "lib/generated/{{}}_solana_types.dart"
        - "lib/generated/{{}}_solana_accounts.dart"
        - "lib/generated/{{}}_solana_instructions.dart"
        - "lib/generated/{{}}_solana_resolution.dart"
        - "lib/generated/{{}}_solana_events.dart"
        - "lib/generated/{{}}_solana_errors.dart"
        - "lib/generated/{{}}_solana_client.dart"
    auto_apply: none
    build_to: source
    defaults:
      generate_for:
        - "lib/idl/**.json"
      options:
        type_prefix: "auto"
        type_suffix: ""
