import 'dart:io';

import 'package:args/command_runner.dart';

import 'generated_output_scanner.dart';
import 'output_planner.dart';
import 'output_transaction.dart';

/// Implements marker-safe generated output cleanup.
final class CleanCommand extends Command<int> {
  /// Creates a cleanup command with replaceable filesystem policies.
  CleanCommand(
    this.output, {
    this.scanner = const GeneratedOutputScanner(),
    this.planner = const CliOutputPlanner(),
    OutputTransactionWriter? writer,
  }) : writer =
           writer ??
           const OutputTransactionWriter(scanner: GeneratedOutputScanner()) {
    argParser
      ..addOption('output', defaultsTo: 'lib/generated')
      ..addFlag('check', negatable: false);
  }

  /// Standard output destination.
  final IOSink output;

  /// Generated-file ownership scanner.
  final GeneratedOutputScanner scanner;

  /// Canonical destination resolver.
  final CliOutputPlanner planner;

  /// Transactional output writer.
  final OutputTransactionWriter writer;

  @override
  String get description => 'Remove only files generated by this tool.';

  @override
  String get name => 'clean';

  @override
  Future<int> run() async {
    final configured = Directory(argResults!['output'] as String).absolute;
    final directory = Directory(await planner.canonicalDestination(configured));
    if (argResults!['check'] as bool) {
      await writer.verifyNoPendingRecovery(directory);
      final generated = await scanner.allOwned(directory);
      for (final file in generated) {
        output.writeln('GENERATED ${file.path}');
      }
      return generated.isEmpty ? 0 : 3;
    }
    await writer.recover(directory);
    final generated = await scanner.allOwned(directory);
    await writer.write(directory, const {}, generated);
    for (final file in generated) {
      output.writeln('REMOVED ${file.path}');
    }
    return 0;
  }
}
